"""
coins.py
Source unique de vérité pour la liste des actifs supportés.
Généré automatiquement par coins_updater.py — ne pas éditer à la main.

Champs :
    ticker  : format Yahoo Finance, pour l'historique (backtest, screening)
    symbol  : symbole affiché
    hl_name : nom de l'actif sur Hyperliquid, pour passer les ordres
    name    : nom lisible

ticker et hl_name diffèrent quand Yahoo suffixe un symbole en collision
(Hyperliquid = "HYPE32196-USD" chez Yahoo, "HYPE" chez Hyperliquid).
"""

COINS = [
    {"ticker": "BTC-USD", "symbol": "BTC", "hl_name": "BTC", "name": "Bitcoin"},
    {"ticker": "ETH-USD", "symbol": "ETH", "hl_name": "ETH", "name": "Ethereum"},
    {"ticker": "ATOM-USD", "symbol": "ATOM", "hl_name": "ATOM", "name": "Cosmos Hub"},
    {"ticker": "DYDX-USD", "symbol": "DYDX", "hl_name": "DYDX", "name": "DYDX"},
    {"ticker": "SOL-USD", "symbol": "SOL", "hl_name": "SOL", "name": "Solana"},
    {"ticker": "AVAX-USD", "symbol": "AVAX", "hl_name": "AVAX", "name": "Avalanche"},
    {"ticker": "BNB-USD", "symbol": "BNB", "hl_name": "BNB", "name": "BNB"},
    {"ticker": "APE-USD", "symbol": "APE", "hl_name": "APE", "name": "ApeCoin"},
    {"ticker": "OP-USD", "symbol": "OP", "hl_name": "OP", "name": "Optimism"},
    {"ticker": "LTC-USD", "symbol": "LTC", "hl_name": "LTC", "name": "Litecoin"},
    {"ticker": "ARB-USD", "symbol": "ARB", "hl_name": "ARB", "name": "Arbitrum"},
    {"ticker": "DOGE-USD", "symbol": "DOGE", "hl_name": "DOGE", "name": "Dogecoin"},
    {"ticker": "INJ-USD", "symbol": "INJ", "hl_name": "INJ", "name": "Injective"},
    {"ticker": "SUI20947-USD", "symbol": "SUI", "hl_name": "SUI", "name": "Sui"},
    {"ticker": "PEPE2027276-USD", "symbol": "PEPE", "hl_name": "kPEPE", "name": "Pepe"},
    {"ticker": "CRV-USD", "symbol": "CRV", "hl_name": "CRV", "name": "Curve DAO"},
    {"ticker": "LDO-USD", "symbol": "LDO", "hl_name": "LDO", "name": "Lido DAO"},
    {"ticker": "LINK-USD", "symbol": "LINK", "hl_name": "LINK", "name": "Chainlink"},
    {"ticker": "STX4847-USD", "symbol": "STX", "hl_name": "STX", "name": "Stacks"},
    {"ticker": "CFX-USD", "symbol": "CFX", "hl_name": "CFX", "name": "Conflux"},
    {"ticker": "GMX11857-USD", "symbol": "GMX", "hl_name": "GMX", "name": "GMX"},
    {"ticker": "SNX-USD", "symbol": "SNX", "hl_name": "SNX", "name": "Synthetix"},
    {"ticker": "XRP-USD", "symbol": "XRP", "hl_name": "XRP", "name": "XRP"},
    {"ticker": "BCH-USD", "symbol": "BCH", "hl_name": "BCH", "name": "Bitcoin Cash"},
    {"ticker": "APT21794-USD", "symbol": "APT", "hl_name": "APT", "name": "Aptos"},
    {"ticker": "AAVE-USD", "symbol": "AAVE", "hl_name": "AAVE", "name": "Aave"},
    {"ticker": "COMP5692-USD", "symbol": "COMP", "hl_name": "COMP", "name": "Compound"},
    {"ticker": "WLD-USD", "symbol": "WLD", "hl_name": "WLD", "name": "Worldcoin"},
    {"ticker": "YGG-USD", "symbol": "YGG", "hl_name": "YGG", "name": "YGG"},
    {"ticker": "TRX-USD", "symbol": "TRX", "hl_name": "TRX", "name": "TRON"},
    {"ticker": "SHIB-USD", "symbol": "SHIB", "hl_name": "kSHIB", "name": "Shiba Inu"},
    {"ticker": "UNI7083-USD", "symbol": "UNI", "hl_name": "UNI", "name": "Uniswap"},
    {"ticker": "SEI-USD", "symbol": "SEI", "hl_name": "SEI", "name": "Sei"},
    {"ticker": "RUNE-USD", "symbol": "RUNE", "hl_name": "RUNE", "name": "THORChain"},
    {"ticker": "ZRO26997-USD", "symbol": "ZRO", "hl_name": "ZRO", "name": "LayerZero"},
    {"ticker": "DOT-USD", "symbol": "DOT", "hl_name": "DOT", "name": "Polkadot"},
    {"ticker": "BANANA28066-USD", "symbol": "BANANA", "hl_name": "BANANA", "name": "BANANA"},
    {"ticker": "TRB-USD", "symbol": "TRB", "hl_name": "TRB", "name": "TRB"},
    {"ticker": "BIGTIME-USD", "symbol": "BIGTIME", "hl_name": "BIGTIME", "name": "BIGTIME"},
    {"ticker": "KAS-USD", "symbol": "KAS", "hl_name": "KAS", "name": "Kaspa"},
    {"ticker": "BLUR-USD", "symbol": "BLUR", "hl_name": "BLUR", "name": "BLUR"},
    {"ticker": "TIA-USD", "symbol": "TIA", "hl_name": "TIA", "name": "Celestia"},
    {"ticker": "BSV-USD", "symbol": "BSV", "hl_name": "BSV", "name": "Bitcoin SV"},
    {"ticker": "ADA-USD", "symbol": "ADA", "hl_name": "ADA", "name": "Cardano"},
    {"ticker": "MINA-USD", "symbol": "MINA", "hl_name": "MINA", "name": "MINA"},
    {"ticker": "POLYX-USD", "symbol": "POLYX", "hl_name": "POLYX", "name": "POLYX"},
    {"ticker": "GAS-USD", "symbol": "GAS", "hl_name": "GAS", "name": "GAS"},
    {"ticker": "PENDLE-USD", "symbol": "PENDLE", "hl_name": "PENDLE", "name": "Pendle"},
    {"ticker": "FET-USD", "symbol": "FET", "hl_name": "FET", "name": "Artificial Superintelligence Alliance"},
    {"ticker": "NEAR-USD", "symbol": "NEAR", "hl_name": "NEAR", "name": "NEAR Protocol"},
    {"ticker": "MEME-USD", "symbol": "MEME", "hl_name": "MEME", "name": "MEME"},
    {"ticker": "ORDI-USD", "symbol": "ORDI", "hl_name": "ORDI", "name": "ORDI"},
    {"ticker": "NEO-USD", "symbol": "NEO", "hl_name": "NEO", "name": "NEO"},
    {"ticker": "ZEN-USD", "symbol": "ZEN", "hl_name": "ZEN", "name": "Horizen"},
    {"ticker": "FIL-USD", "symbol": "FIL", "hl_name": "FIL", "name": "Filecoin"},
    {"ticker": "PYTH-USD", "symbol": "PYTH", "hl_name": "PYTH", "name": "Pyth Network"},
    {"ticker": "SUSHI-USD", "symbol": "SUSHI", "hl_name": "SUSHI", "name": "SUSHI"},
    {"ticker": "IMX10603-USD", "symbol": "IMX", "hl_name": "IMX", "name": "IMX"},
    {"ticker": "BONK-USD", "symbol": "BONK", "hl_name": "kBONK", "name": "Bonk"},
    {"ticker": "GMT18069-USD", "symbol": "GMT", "hl_name": "GMT", "name": "GMT"},
    {"ticker": "SUPER8290-USD", "symbol": "SUPER", "hl_name": "SUPER", "name": "SUPER"},
    {"ticker": "JUP-USD", "symbol": "JUP", "hl_name": "JUP", "name": "Jupiter"},
    {"ticker": "LUNC-USD", "symbol": "LUNC", "hl_name": "kLUNC", "name": "Terra Luna Classic"},
    {"ticker": "RSR-USD", "symbol": "RSR", "hl_name": "RSR", "name": "RSR"},
    {"ticker": "JTO-USD", "symbol": "JTO", "hl_name": "JTO", "name": "Jito"},
    {"ticker": "WIF-USD", "symbol": "WIF", "hl_name": "WIF", "name": "dogwifhat"},
    {"ticker": "CAKE-USD", "symbol": "CAKE", "hl_name": "CAKE", "name": "PancakeSwap"},
    {"ticker": "PEOPLE-USD", "symbol": "PEOPLE", "hl_name": "PEOPLE", "name": "PEOPLE"},
    {"ticker": "ENS-USD", "symbol": "ENS", "hl_name": "ENS", "name": "Ethereum Name Service"},
    {"ticker": "ETC-USD", "symbol": "ETC", "hl_name": "ETC", "name": "Ethereum Classic"},
    {"ticker": "XAI-USD", "symbol": "XAI", "hl_name": "XAI", "name": "XAI"},
    {"ticker": "MANTA-USD", "symbol": "MANTA", "hl_name": "MANTA", "name": "MANTA"},
    {"ticker": "UMA-USD", "symbol": "UMA", "hl_name": "UMA", "name": "UMA"},
    {"ticker": "ONDO-USD", "symbol": "ONDO", "hl_name": "ONDO", "name": "Ondo"},
    {"ticker": "ALT29073-USD", "symbol": "ALT", "hl_name": "ALT", "name": "ALT"},
    {"ticker": "ZETA-USD", "symbol": "ZETA", "hl_name": "ZETA", "name": "ZETA"},
    {"ticker": "DYM-USD", "symbol": "DYM", "hl_name": "DYM", "name": "DYM"},
    {"ticker": "W-USD", "symbol": "W", "hl_name": "W", "name": "W"},
    {"ticker": "STRK-USD", "symbol": "STRK", "hl_name": "STRK", "name": "Starknet"},
    {"ticker": "TAO22974-USD", "symbol": "TAO", "hl_name": "TAO", "name": "Bittensor"},
    {"ticker": "AR-USD", "symbol": "AR", "hl_name": "AR", "name": "Arweave"},
    {"ticker": "FLOKI-USD", "symbol": "FLOKI", "hl_name": "kFLOKI", "name": "kFLOKI"},
    {"ticker": "BOME-USD", "symbol": "BOME", "hl_name": "BOME", "name": "BOME"},
    {"ticker": "ETHFI-USD", "symbol": "ETHFI", "hl_name": "ETHFI", "name": "Ether.fi"},
    {"ticker": "ENA-USD", "symbol": "ENA", "hl_name": "ENA", "name": "Ethena"},
    {"ticker": "MNT-USD", "symbol": "MNT", "hl_name": "MNT", "name": "Mantle"},
    {"ticker": "TNSR-USD", "symbol": "TNSR", "hl_name": "TNSR", "name": "TNSR"},
    {"ticker": "SAGA30372-USD", "symbol": "SAGA", "hl_name": "SAGA", "name": "SAGA"},
    {"ticker": "MERL-USD", "symbol": "MERL", "hl_name": "MERL", "name": "MERL"},
    {"ticker": "HBAR-USD", "symbol": "HBAR", "hl_name": "HBAR", "name": "Hedera"},
    {"ticker": "POPCAT28782-USD", "symbol": "POPCAT", "hl_name": "POPCAT", "name": "POPCAT"},
    {"ticker": "EIGEN-USD", "symbol": "EIGEN", "hl_name": "EIGEN", "name": "EigenCloud (prev. EigenLayer)"},
    {"ticker": "REZ-USD", "symbol": "REZ", "hl_name": "REZ", "name": "REZ"},
    {"ticker": "NOT-USD", "symbol": "NOT", "hl_name": "NOT", "name": "NOT"},
    {"ticker": "TURBO-USD", "symbol": "TURBO", "hl_name": "TURBO", "name": "TURBO"},
    {"ticker": "BRETT28891-USD", "symbol": "BRETT", "hl_name": "BRETT", "name": "BRETT"},
    {"ticker": "IO29835-USD", "symbol": "IO", "hl_name": "IO", "name": "IO"},
    {"ticker": "ZK24091-USD", "symbol": "ZK", "hl_name": "ZK", "name": "ZK"},
    {"ticker": "RENDER-USD", "symbol": "RENDER", "hl_name": "RENDER", "name": "Render"},
    {"ticker": "POL28321-USD", "symbol": "POL", "hl_name": "POL", "name": "POL (ex-MATIC)"},
    {"ticker": "CELO-USD", "symbol": "CELO", "hl_name": "CELO", "name": "CELO"},
    {"ticker": "HMSTR-USD", "symbol": "HMSTR", "hl_name": "HMSTR", "name": "HMSTR"},
    {"ticker": "NEIRO32521-USD", "symbol": "NEIRO", "hl_name": "kNEIRO", "name": "kNEIRO"},
    {"ticker": "GOAT-USD", "symbol": "GOAT", "hl_name": "GOAT", "name": "GOAT"},
    {"ticker": "MOODENG33076-USD", "symbol": "MOODENG", "hl_name": "MOODENG", "name": "MOODENG"},
    {"ticker": "GRASS32276-USD", "symbol": "GRASS", "hl_name": "GRASS", "name": "Grass"},
    {"ticker": "PURR40003-USD", "symbol": "PURR", "hl_name": "PURR", "name": "PURR"},
    {"ticker": "PNUT-USD", "symbol": "PNUT", "hl_name": "PNUT", "name": "PNUT"},
    {"ticker": "XLM-USD", "symbol": "XLM", "hl_name": "XLM", "name": "Stellar"},
    {"ticker": "SAND-USD", "symbol": "SAND", "hl_name": "SAND", "name": "The Sandbox"},
    {"ticker": "IOTA-USD", "symbol": "IOTA", "hl_name": "IOTA", "name": "IOTA"},
    {"ticker": "ALGO-USD", "symbol": "ALGO", "hl_name": "ALGO", "name": "Algorand"},
    {"ticker": "HYPE32196-USD", "symbol": "HYPE", "hl_name": "HYPE", "name": "Hyperliquid"},
    {"ticker": "MOVE32452-USD", "symbol": "MOVE", "hl_name": "MOVE", "name": "MOVE"},
    {"ticker": "VIRTUAL-USD", "symbol": "VIRTUAL", "hl_name": "VIRTUAL", "name": "Virtuals Protocol"},
    {"ticker": "PENGU34466-USD", "symbol": "PENGU", "hl_name": "PENGU", "name": "Pudgy Penguins"},
    {"ticker": "USUAL-USD", "symbol": "USUAL", "hl_name": "USUAL", "name": "USUAL"},
    {"ticker": "FARTCOIN-USD", "symbol": "FARTCOIN", "hl_name": "FARTCOIN", "name": "Fartcoin"},
    {"ticker": "AIXBT-USD", "symbol": "AIXBT", "hl_name": "AIXBT", "name": "AIXBT"},
    {"ticker": "BIO34812-USD", "symbol": "BIO", "hl_name": "BIO", "name": "BIO"},
    {"ticker": "GRIFFAIN-USD", "symbol": "GRIFFAIN", "hl_name": "GRIFFAIN", "name": "GRIFFAIN"},
    {"ticker": "SPX20-USD", "symbol": "SPX", "hl_name": "SPX", "name": "SPX6900"},
    {"ticker": "S32684-USD", "symbol": "S", "hl_name": "S", "name": "Sonic"},
    {"ticker": "MORPHO34104-USD", "symbol": "MORPHO", "hl_name": "MORPHO", "name": "Morpho"},
    {"ticker": "TRUMP35336-USD", "symbol": "TRUMP", "hl_name": "TRUMP", "name": "Official Trump"},
    {"ticker": "MELANIA-USD", "symbol": "MELANIA", "hl_name": "MELANIA", "name": "MELANIA"},
    {"ticker": "ANIME35319-USD", "symbol": "ANIME", "hl_name": "ANIME", "name": "ANIME"},
    {"ticker": "VVV35509-USD", "symbol": "VVV", "hl_name": "VVV", "name": "Venice Token"},
    {"ticker": "BERA-USD", "symbol": "BERA", "hl_name": "BERA", "name": "BERA"},
    {"ticker": "LAYER-USD", "symbol": "LAYER", "hl_name": "LAYER", "name": "LAYER"},
    {"ticker": "KAITO-USD", "symbol": "KAITO", "hl_name": "KAITO", "name": "KAITO"},
    {"ticker": "NIL35702-USD", "symbol": "NIL", "hl_name": "NIL", "name": "NIL"},
    {"ticker": "PAXG-USD", "symbol": "PAXG", "hl_name": "PAXG", "name": "PAX Gold"},
    {"ticker": "BABY10334-USD", "symbol": "BABY", "hl_name": "BABY", "name": "BABY"},
    {"ticker": "WCT33152-USD", "symbol": "WCT", "hl_name": "WCT", "name": "WCT"},
    {"ticker": "HYPER36281-USD", "symbol": "HYPER", "hl_name": "HYPER", "name": "HYPER"},
    {"ticker": "ZORA35931-USD", "symbol": "ZORA", "hl_name": "ZORA", "name": "ZORA"},
    {"ticker": "INIT-USD", "symbol": "INIT", "hl_name": "INIT", "name": "INIT"},
    {"ticker": "NXPC-USD", "symbol": "NXPC", "hl_name": "NXPC", "name": "NXPC"},
    {"ticker": "SOPH-USD", "symbol": "SOPH", "hl_name": "SOPH", "name": "SOPH"},
    {"ticker": "RESOLV-USD", "symbol": "RESOLV", "hl_name": "RESOLV", "name": "RESOLV"},
    {"ticker": "SYRUP-USD", "symbol": "SYRUP", "hl_name": "SYRUP", "name": "Maple Finance"},
    {"ticker": "PUMP36507-USD", "symbol": "PUMP", "hl_name": "PUMP", "name": "Pump.fun"},
    {"ticker": "PROVE-USD", "symbol": "PROVE", "hl_name": "PROVE", "name": "PROVE"},
    {"ticker": "XPL-USD", "symbol": "XPL", "hl_name": "XPL", "name": "Plasma"},
    {"ticker": "WLFI33251-USD", "symbol": "WLFI", "hl_name": "WLFI", "name": "World Liberty Financial"},
    {"ticker": "LINEA-USD", "symbol": "LINEA", "hl_name": "LINEA", "name": "LINEA"},
    {"ticker": "SKY-USD", "symbol": "SKY", "hl_name": "SKY", "name": "Sky"},
    {"ticker": "ASTER36341-USD", "symbol": "ASTER", "hl_name": "ASTER", "name": "Aster"},
    {"ticker": "AVNT-USD", "symbol": "AVNT", "hl_name": "AVNT", "name": "AVNT"},
    {"ticker": "STBL-USD", "symbol": "STBL", "hl_name": "STBL", "name": "STBL"},
    {"ticker": "0G-USD", "symbol": "0G", "hl_name": "0G", "name": "0G"},
    {"ticker": "HEMI-USD", "symbol": "HEMI", "hl_name": "HEMI", "name": "HEMI"},
    {"ticker": "APEX19843-USD", "symbol": "APEX", "hl_name": "APEX", "name": "APEX"},
    {"ticker": "2Z-USD", "symbol": "2Z", "hl_name": "2Z", "name": "DoubleZero"},
    {"ticker": "ZEC-USD", "symbol": "ZEC", "hl_name": "ZEC", "name": "Zcash"},
    {"ticker": "MON-USD", "symbol": "MON", "hl_name": "MON", "name": "Monad"},
    {"ticker": "MET-USD", "symbol": "MET", "hl_name": "MET", "name": "MET"},
    {"ticker": "MEGA38770-USD", "symbol": "MEGA", "hl_name": "MEGA", "name": "MEGA"},
    {"ticker": "CC37263-USD", "symbol": "CC", "hl_name": "CC", "name": "Canton"},
    {"ticker": "ICP-USD", "symbol": "ICP", "hl_name": "ICP", "name": "Internet Computer"},
    {"ticker": "AERO-USD", "symbol": "AERO", "hl_name": "AERO", "name": "Aerodrome Finance"},
    {"ticker": "STABLE38892-USD", "symbol": "STABLE", "hl_name": "STABLE", "name": "​​Stable"},
    {"ticker": "FOGO-USD", "symbol": "FOGO", "hl_name": "FOGO", "name": "FOGO"},
    {"ticker": "LIT6833-USD", "symbol": "LIT", "hl_name": "LIT", "name": "Lighter"},
    {"ticker": "XMR-USD", "symbol": "XMR", "hl_name": "XMR", "name": "Monero"},
    {"ticker": "AXS-USD", "symbol": "AXS", "hl_name": "AXS", "name": "Axie Infinity"},
    {"ticker": "DASH-USD", "symbol": "DASH", "hl_name": "DASH", "name": "Dash"},
    {"ticker": "SKR39377-USD", "symbol": "SKR", "hl_name": "SKR", "name": "Seeker"},
    {"ticker": "AZTEC-USD", "symbol": "AZTEC", "hl_name": "AZTEC", "name": "AZTEC"},
    {"ticker": "CHIP39870-USD", "symbol": "CHIP", "hl_name": "CHIP", "name": "CHIP"},
    {"ticker": "GRAM-USD", "symbol": "GRAM", "hl_name": "GRAM", "name": "Gram (prev. Toncoin)"},
    {"ticker": "CASHCAT-USD", "symbol": "CASHCAT", "hl_name": "CASHCAT", "name": "Cash Cat"},
    {"ticker": "PONS-USD", "symbol": "PONS", "hl_name": "PONS", "name": "Pons"},
]

# ---------------------------------------------------------------------------
# Indices boursiers — tickers Yahoo Finance, non tradables sur Hyperliquid
# ---------------------------------------------------------------------------
INDICES = [
    {"ticker": "^GSPC", "symbol": "SP500", "hl_name": None, "name": "S&P 500"},
    {"ticker": "^IXIC", "symbol": "NASDAQ", "hl_name": None, "name": "Nasdaq Composite"},
    {"ticker": "^STOXX50E", "symbol": "STOXX50", "hl_name": None, "name": "Euro Stoxx 50"},
    {"ticker": "^FCHI", "symbol": "CAC40", "hl_name": None, "name": "CAC 40"},
    {"ticker": "^GDAXI", "symbol": "DAX", "hl_name": None, "name": "DAX 40"},
    {"ticker": "^DJI", "symbol": "DOW", "hl_name": None, "name": "Dow Jones"},
    {"ticker": "^FTSE", "symbol": "FTSE100", "hl_name": None, "name": "FTSE 100"},
    {"ticker": "^N225", "symbol": "NIKKEI", "hl_name": None, "name": "Nikkei 225"},
]

# Liste complète = cryptos + indices
ALL_ASSETS = COINS + INDICES
